#!/usr/bin/env python3
"""Checks that a pull request carries only the owner's own authorship.

Fails when:
- a commit's author or committer is not OWNER_NAME <OWNER_EMAIL>;
- a commit message has a Co-Authored-By trailer, a line that starts with
  "Generated with" or "Generated by", a line that starts with "Requested
  by" and mentions a thread, or a link to one of BLOCKED_HOSTS;
- the pull request description has a hidden HTML comment (<!-- ... -->) or
  any of the lines above.

A line counts as starting with a phrase when only punctuation, symbols or
spaces come before it, so "_Generated by ..._" and "> Requested by ..."
count, while "Files generated by the build" does not.

Every commit in BASE..HEAD is checked, merge commits included; commits
already on the base branch are not.

Usage:
  tools/check_authorship.py --event FILE
      FILE is the pull_request event payload (GITHUB_EVENT_PATH in Actions):
      base and head commits and the description come from it.
  tools/check_authorship.py [--body-file FILE] BASE [HEAD]
      Checks BASE..HEAD (HEAD defaults to HEAD) in the current repository,
      and the description in FILE if given.
"""

import argparse
import json
import os
import re
import secrets
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

OWNER_NAME = "Alejandro Brunacci"
OWNER_EMAIL = "abrunacci87@gmail.com"
BLOCKED_HOSTS = ("claude.ai",)

# (pattern, what it found), matched against each line on its own.
LINE_RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^\s*co-authored-by\s*:", re.I), "a Co-Authored-By trailer"),
    (re.compile(r"^[\W_]*generated\s+(with|by)\b", re.I), 'a "Generated with/by" line'),
    (
        re.compile(r"^[\W_]*requested\s+by\b.*\bthread\b", re.I),
        'a "Requested by ... thread" line',
    ),
] + [
    (
        re.compile(rf"(?<![\w.-])(?:[\w-]+\.)*{re.escape(host)}(?![\w-])", re.I),
        f"a link to {host}",
    )
    for host in BLOCKED_HOSTS
]
HTML_COMMENT = re.compile(r"<!--")

# Field and record separators for git log: they cannot appear in names,
# addresses or commit messages.
FIELD = "\x1f"
RECORD = "\x1e"


@dataclass
class Commit:
    sha: str
    author: str
    committer: str
    message: str

    @property
    def short(self) -> str:
        return self.sha[:12]

    @property
    def subject(self) -> str:
        return self.message.splitlines()[0] if self.message else ""


OWNER = f"{OWNER_NAME} <{OWNER_EMAIL}>"

FIX_IDENTITY = f"""\
  To fix it, set your identity and rewrite the commits of this branch:
    git config user.name "{OWNER_NAME}"
    git config user.email "{OWNER_EMAIL}"
    git rebase --exec "git commit --amend --no-edit --reset-author" {{base}}
    git push --force-with-lease
  Commits made by GitHub itself (the "Update branch" button, edits in the
  web editor) have GitHub as committer: merge or edit locally instead."""

FIX_MESSAGE = """\
  To fix it, remove those lines from the message and push again. For the
  last commit, run git commit --amend; for an earlier one, run
  git rebase -i {base} and mark the commit as "reword". Then:
    git push --force-with-lease"""

FIX_BODY = """\
  To fix it, edit the pull request description and remove it: the check
  runs again on every edit."""


def find_lines(text: str) -> list[tuple[int, str, str]]:
    """(line number, what was found, the line) for every rule a line breaks."""
    found = []
    for number, line in enumerate(text.splitlines(), start=1):
        for pattern, what in LINE_RULES:
            if pattern.search(line):
                found.append((number, what, line.strip()))
    return found


def check_commit(commit: Commit) -> list[str]:
    problems = []
    if commit.author != OWNER:
        problems.append(f"author is {commit.author}, not {OWNER}")
    if commit.committer != OWNER:
        problems.append(f"committer is {commit.committer}, not {OWNER}")
    return problems


def check_commits(commits: list[Commit], base: str) -> list[str]:
    """One error text per commit that breaks a rule, with how to fix it."""
    errors = []
    for commit in commits:
        identity = check_commit(commit)
        lines = find_lines(commit.message)
        if not identity and not lines:
            continue
        text = [f'Commit {commit.short} "{commit.subject}":']
        text += [f"  - {problem}" for problem in identity]
        text += [
            f"  - message line {number} has {what}: {line}"
            for number, what, line in lines
        ]
        if identity:
            text.append(FIX_IDENTITY.format(base=base))
        if lines:
            text.append(FIX_MESSAGE.format(base=base))
        errors.append("\n".join(text))
    return errors


def check_body(body: str) -> list[str]:
    """One error text for the description, if it breaks a rule."""
    problems = []
    for number, line in enumerate(body.splitlines(), start=1):
        if HTML_COMMENT.search(line):
            problems.append(f"line {number} has a hidden HTML comment: {line.strip()}")
    problems += [
        f"line {number} has {what}: {line}" for number, what, line in find_lines(body)
    ]
    if not problems:
        return []
    text = ["Pull request description:"]
    text += [f"  - {problem}" for problem in problems]
    text.append(FIX_BODY)
    return ["\n".join(text)]


def read_commits(base: str, head: str) -> list[Commit]:
    fields = FIELD.join(["%H", "%an <%ae>", "%cn <%ce>", "%B"])
    output = subprocess.run(
        ["git", "log", f"--format={fields}{RECORD}", f"{base}..{head}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    commits = []
    for record in output.split(RECORD):
        if not record.strip():
            continue
        sha, author, committer, message = record.lstrip("\n").split(FIELD, 3)
        commits.append(Commit(sha, author, committer, message.strip()))
    return commits


def escape(text: str) -> str:
    """Text as the data of a workflow command."""
    return text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Check a pull request's authorship.")
    parser.add_argument("--event", type=Path, help="pull_request event payload")
    parser.add_argument("--body-file", type=Path, help="pull request description")
    parser.add_argument("base", nargs="?")
    parser.add_argument("head", nargs="?", default="HEAD")
    args = parser.parse_args(argv[1:])

    if args.event:
        pull_request = json.loads(args.event.read_text(encoding="utf-8"))[
            "pull_request"
        ]
        base = pull_request["base"]["sha"]
        head = pull_request["head"]["sha"]
        body = pull_request.get("body") or ""
    elif args.base:
        base, head = args.base, args.head
        body = args.body_file.read_text(encoding="utf-8") if args.body_file else ""
    else:
        parser.error("give --event FILE, or BASE [HEAD]")

    commits = read_commits(base, head)
    errors = check_commits(commits, base) + check_body(body)
    in_actions = os.environ.get("GITHUB_ACTIONS") == "true"
    # Commit messages and the description are quoted in the log: while they
    # print, the runner must not take any of their lines for a command.
    token = secrets.token_hex(16)
    if in_actions:
        print(f"::stop-commands::{token}")
    for error in errors:
        print(error, end="\n\n")
    if in_actions:
        print(f"::{token}::")
        # One annotation per problem on the run's page; the full text,
        # with how to fix it, is in the log.
        for error in errors:
            header, *details = error.splitlines()
            for problem in (d for d in details if d.startswith("  - ")):
                annotation = f"{header} {problem.removeprefix('  - ')}"
                print(f"::error title=Authorship::{escape(annotation)}")
    print(
        f"checked {len(commits)} commit(s) and the description: "
        f"{len(errors)} problem(s)"
    )
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
