"""Tests for check_authorship.py. Run with: python3 -m unittest discover tools"""

import contextlib
import io
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from check_authorship import OWNER_EMAIL, OWNER_NAME, check_body, main

OTHER = ("Someone Else", "someone@example.com")


class CheckAuthorshipTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.repo = Path(self.tmp.name)
        self.cwd = os.getcwd()
        os.chdir(self.repo)
        self.git("init", "-q", "-b", "main")
        self.base = self.commit("Initial commit")

    def tearDown(self) -> None:
        os.chdir(self.cwd)
        self.tmp.cleanup()

    def git(self, *args: str, env: dict[str, str] | None = None) -> str:
        # No hooks: a global commit-msg hook could rewrite the messages under
        # test.
        return subprocess.run(
            ["git", "-c", "core.hooksPath=/dev/null", "-c", "commit.gpgsign=false"]
            + list(args),
            check=True,
            capture_output=True,
            text=True,
            env={**os.environ, **(env or {})},
        ).stdout.strip()

    def commit(
        self,
        message: str,
        author: tuple[str, str] = (OWNER_NAME, OWNER_EMAIL),
        committer: tuple[str, str] = (OWNER_NAME, OWNER_EMAIL),
    ) -> str:
        env = {
            "GIT_AUTHOR_NAME": author[0],
            "GIT_AUTHOR_EMAIL": author[1],
            "GIT_COMMITTER_NAME": committer[0],
            "GIT_COMMITTER_EMAIL": committer[1],
        }
        self.git("commit", "-q", "--allow-empty", "-m", message, env=env)
        return self.git("rev-parse", "HEAD")

    def run_check(self, body: str = "") -> tuple[int, str]:
        event = self.repo / "event.json"
        head = self.git("rev-parse", "HEAD")
        payload = {"base": {"sha": self.base}, "head": {"sha": head}, "body": body}
        event.write_text(json.dumps({"pull_request": payload}), encoding="utf-8")
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            code = main(["check_authorship.py", "--event", str(event)])
        return code, out.getvalue()

    def test_own_commits_pass(self) -> None:
        self.commit("Add the photo to the header\n\nThe files are generated by Astro.")
        self.commit("Link the projects")
        code, out = self.run_check("Adds the photo.\n\nGenerated files stay out.")
        self.assertEqual(code, 0, out)
        self.assertIn("checked 2 commit(s)", out)

    def test_commits_on_the_base_branch_are_not_checked(self) -> None:
        self.git("commit", "-q", "--allow-empty", "--amend", "-m", "Co-Authored-By: x")
        self.base = self.git("rev-parse", "HEAD")
        self.commit("Add a project")
        self.assertEqual(self.run_check()[0], 0)

    def test_other_author_fails(self) -> None:
        sha = self.commit("Add a project", author=OTHER)
        code, out = self.run_check()
        self.assertEqual(code, 1)
        self.assertIn(f'Commit {sha[:12]} "Add a project"', out)
        self.assertIn("author is Someone Else <someone@example.com>", out)
        self.assertIn("--reset-author", out)
        self.assertNotIn("committer is", out)

    def test_other_committer_fails(self) -> None:
        self.commit("Merge main", committer=("GitHub", "noreply@github.com"))
        code, out = self.run_check()
        self.assertEqual(code, 1)
        self.assertIn("committer is GitHub <noreply@github.com>", out)

    def test_same_name_other_email_fails(self) -> None:
        self.commit("Add a project", author=(OWNER_NAME, "other@example.com"))
        self.assertEqual(self.run_check()[0], 1)

    def test_attribution_lines_in_messages_fail(self) -> None:
        messages = {
            "Co-Authored-By": "Fix it\n\nCo-authored-by: Bot <bot@example.com>",
            "Generated with": "Fix it\n\n🤖 Generated with [Some Tool](https://x.y)",
            "Generated by": "Fix it\n\n_Generated by Some Tool_",
            "Requested by": "Fix it\n\nRequested by **Someone** · [project thread](x)",
            "link": "Fix it\n\nSee https://claude.ai/code/session_1",
        }
        for name, message in messages.items():
            with self.subTest(name):
                self.git("reset", "-q", "--hard", self.base)
                self.commit(message)
                code, out = self.run_check()
                self.assertEqual(code, 1, out)
                self.assertIn("message line 3 has", out)
                self.assertIn("git rebase -i", out)

    def test_phrases_inside_a_sentence_pass(self) -> None:
        self.commit(
            "Explain the build\n\nThe images are generated by render-images.sh.\n"
            "Requested by the design review."
        )
        self.assertEqual(self.run_check()[0], 0)

    def test_hidden_comment_in_description_fails(self) -> None:
        self.commit("Add a project")
        code, out = self.run_check("Adds it.\n<!-- marker: {} -->\n")
        self.assertEqual(code, 1)
        self.assertIn("line 2 has a hidden HTML comment", out)
        self.assertIn("edit the pull request description", out)

    def test_attribution_lines_in_description_fail(self) -> None:
        for body in [
            "Adds it.\n\nCo-Authored-By: Bot <bot@example.com>",
            "Adds it.\n\n---\n_Generated with Some Tool_",
            "_Requested by **A** · [project thread](https://example.com)_",
            "Details: https://claude.ai/code/session_1",
        ]:
            with self.subTest(body):
                self.assertEqual(len(check_body(body)), 1)

    def test_missing_description_passes(self) -> None:
        self.commit("Add a project")
        event = self.repo / "event.json"
        payload = {
            "base": {"sha": self.base},
            "head": {"sha": self.git("rev-parse", "HEAD")},
            "body": None,
        }
        event.write_text(json.dumps({"pull_request": payload}), encoding="utf-8")
        with contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(main(["check_authorship.py", "--event", str(event)]), 0)

    def test_every_problem_is_reported(self) -> None:
        self.commit("One", author=OTHER)
        self.commit("Two\n\nCo-Authored-By: Bot <bot@example.com>")
        code, out = self.run_check("<!-- x -->")
        self.assertEqual(code, 1)
        self.assertIn("3 problem(s)", out)

    def test_quoted_lines_cannot_issue_runner_commands(self) -> None:
        self.commit("::add-mask::secret", author=OTHER)
        os.environ["GITHUB_ACTIONS"] = "true"
        try:
            _, out = self.run_check()
        finally:
            del os.environ["GITHUB_ACTIONS"]
        lines = out.splitlines()
        token = lines[0].removeprefix("::stop-commands::")
        self.assertTrue(lines[0].startswith("::stop-commands::"))
        quoted = next(i for i, line in enumerate(lines) if "add-mask" in line)
        self.assertLess(quoted, lines.index(f"::{token}::"))
        self.assertIn("::error title=Authorship::Commit ", out)


if __name__ == "__main__":
    unittest.main()
